window.onload = function() {
  const oldH1 = document.querySelector("h1");
  oldH1.remove();
  const newH1 = document.createElement("h1");
  newH1.append("Webpage Recreation Practice");
  const newP = document.createElement("p");
  newP.append("The HTML of this page was created with JavaScript.");
  const newImage = document.createElement("img");
  newImage.src = "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/202984001/900";
  newImage.alt = "This is an image of a Multicolored Tanager bird from birdsoftheworld.org";
  newImage.style = "width:50%";
  const newH1Two = document.createElement("h1");
  newH1Two.append("Facts about the Multicolored Tanager");
  const newList = document.createElement("ul");
  const bodySpot = document.querySelector("body");
  newList.setAttribute("id", "factList");
  bodySpot.append(newH1, newP, newImage, newH1Two, newList);
  const listPoint1 = document.createElement("li");
  listPoint1.append("It is endemic to the mountains of Colombia.");
  const listPoint2 = document.createElement("li");
  listPoint2.append("It usually searches for insects on the underside of leaves of outer limbs while clinging to leaves with its feet.");
  document.getElementById("factList").append(listPoint1, listPoint2);
  const newH2 = document.createElement("h2");
  newH2.append("Source");
  const newLink = document.createElement("a");
  newLink.href = "https://en.wikipedia.org/wiki/Multicoloured_tanager";
  const wikipedia = document.createTextNode("Wikipedia");
  newLink.appendChild(wikipedia);
  bodySpot.append(newH2, newLink);
};